branch-defaults:
  master:
    environment: qbotio-api-dev
global:
  application_name: qbotio-api
  default_ec2_keyname: qbotio-aws-eb
  default_platform: Python 3.4
  default_region: us-west-1
  profile: eb-cli
  sc: git
